version: '3.9'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    env_file:
      - backend/.env
    command: npm start

  client:
    build: ./client/
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - '3000:3000'
    env_file:
      - client/.env
