version: '3.9'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  backend:
    build: ./backend/
    # image: sayinmehmet47/backend-kitapkurdu-1:latest
    volumes:
      - ./backend/:/app
    ports:
      - '5000:5000'
    env_file:
      - backend/.env
    command: npm start

  client:
    build: ./client/

    # image: sayinmehmet47/client-kitapkurdu-1:latest
    volumes:
      - ./client/:/app
    depends_on:
      - backend
    ports:
      - '3000:3000'

    env_file:
      - client/.env
