---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jwt-secret
  namespace: kitapkurdu
spec:
  encryptedData:
    JWT_SECRET: AgDi3MjT2UD5Slyv0b4ZE4sHhfIHmVw8BRF9ZSNJ4wS9i12L9q22S6l79ZQkFfHQVruN1XANNoLsWjrZ56Ky37p9/JykO0a8FrI3/1pdY45XJ9k1IMWQrQL3dtJ6nBDcHd5Sa9lRDKLytA32yM7wG8k7dI+3ZYEDd0I/rEuvF7dIFl1AWZy+TKYbOER2+xoxCKuWjA/X5N0IPFj+KWFBlfkbajv1aj1BTdTXcnxlYrDhIeX1dlb7cKESOKfzYSUfrp0F6SDyj7lfj/Xdy7L6l0Mo87QSUJSWZ1bAb7Y62HfxZTdnXlEeBHD++Rz+zrwmH+OIfS/ayG9d4EktGg/XkAXgZNs1To+63Idf3nXUjzpDbDdBemcG4H2h3iZ/iSnqC6jsn7qTZGMxcfu/FIz6AbaIpter4iSVIpG8Pk59zeN9k41RdXQ6rUKsjuyKGX6IqIrmDXJTx8sYxkbmO0h3vxI1fk0Fu0pKm2RpHUJRUhGpa7aFGCt8aTUyTgbOUIe9ij9woDLOXPjzcG0gwci8idnZ8HnsF256XVQb2mcXFTPQw6U1xyGHNznii+V6FLXczjj+xFiXDa4RZucVb06UBG+LdYU0VX3vZBgUKJAWrj6O/ZUxSuR9W0Sw4WQD5DpRbdoDVYYEl/CSjEVzK6vRCEUi6zb3mb9TsB40Zl+rGd5+niwNRmjm1/W5EGTe12u7poGQgPzFKLVonNvC+Bqs
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:JWT_SECRET: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2024-03-11T11:16:45Z"
      name: jwt-secret
      namespace: kitapkurdu
