---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongo-uri
  namespace: kitapkurdu
spec:
  encryptedData:
    MONGO_URI: AgABVZN59cZtiwmdGKW20cQYKzNVttbs9ZTWJUUtLOEjcuIgxpDDjEu2UyJwkzSsGGLy5eFBKkmwPf6+nDY50DuL5EYmHky/FfDfqciXEvEwzesqTCcP8tPG4kzj//YG+i7rQ6WFmLv3PsS94D2oG5bUsYn7UerL/KVON/tTdqYrCHJKNoGPisnRfD4Rldv0Sc9I/NERGTGm8gi4OViHMFp0tyn6dQomm563dp1K2KqD0vMH1Mp/6dTaGteWVuwvf8Usuo2a0hqVCohfp4W/2Dyt2r0YcleaEn6IDqOuwiEaGRP35zWCBnSzZHCj7UMLIz+L7Q58FNgR/FwB87M7YHZpePf6NLZq5jmjq0JrsTc0Vg9o1rW3k+T2Mq3qvSRux04opn74iNOPO0UHR6GBTTcBYIWzVbIa7Qvg42AML3cBp11UmqZB35EbtcdILes/e58ieJ6v7JPRdcmHBFvUGQFtBm0KsClZKe3tkxH8yzByEnIIyvyeyoQUvu3iJFKB3Fx9rGBr5hNlzXZ6Wz4Ng8S60mT64k/4E7t5R2Xog+S9uPjvIBYYevVWOvazZ2u54kl2qcc02hAO1TsSwos697ALfLZJbs/8dVXNteKtvaxf36BiDtY7UuaT7JmIiBMwwN2ZfAurVU5K4qIFgl3PrQ0A8FH4OTNwQUmFkkqc/2MSXiTn2GHfSiDI7J4NKcBV/aSySCPeRUH5UMlPlAKgu2syNqAmgFgKlEBE5LkMzqY4uvOW2emTArmKCOlwV6F4fHMcmmFnchfx0o9Xa1p4FCwjNLevdpM6eF5H3VR/gebKRoK0URJI4vsdPq1yAeIa4ikXzrjT/AhY7A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2024-03-11T12:31:00Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:MONGO_URI: {}
        manager: agent
        operation: Update
        time: "2024-03-11T13:06:17Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:metadata:
            f:annotations:
              .: {}
              f:kubectl.kubernetes.io/last-applied-configuration: {}
        manager: kubectl-client-side-apply
        operation: Update
        time: "2024-03-18T09:59:51Z"
      name: mongo-uri
      namespace: kitapkurdu
