---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: react-app-public-emailjs-template-id
  namespace: kitapkurdu
spec:
  encryptedData:
    value: AgDCP4vPaGIN//MdxgX4K0Ud8M/qpcpVpfTZF/nBZooMLlNuPgM4BmDfgmoS6/kfKZpYk23wZ3derUDi+wwx3VNab7NXDLi/Sp3Li89e/5Nf4bGYKwI7z8pE0yVic07Xf+uP/Dp8E6ieUUQ/p2WWRPz0xcqCTrEeQNVxplAymfxFD+rh5+tAymlJ5M6Vzs3m/9BFyKt8UGuU6W+ExwH2ZNMn7M0M+D5gHqMnpgfNhyqRUvoBkOGLYuzFBY8YHDdgXiAXAcWKdiaeVMdK9NzQhko+FMppnw00wAZAr8pPzJF0JCb/uCq01IZzD38NDREiFU/HsdMuvbwc/6hD8CAEn7UCFUaSW0jxg9973cZNCtEVmB6tP8kbmgw2gCXXMUUS+OqbCiLNxj4AH0ATrqlH60I4Yot8Y0AIOWp+oJdeJIt8XcTq0oU06ePQPaUXBt27Mv6+C5F3sCfs/tPOLiO+lV/ZMHZI4ltzVaz6ocD4/Z8ZEIY4gyNhYsKCo/WI0GvrfJRPE4XrCJBzLvu8QAciQ/L3qYmHUMTxQxsGjz/TZ85XhZsRgXItVKJ9xY0KIdDPvLqlyndHmKXtBe3QbemOSR5xXiXoRkr0CFH68FrNuog2gn67qaBKKDnEUOZ/cLzR7aJM30JKH5vISHR93hg16zI5RR9nmxN57MIFXx9z3JwE1nPc61bbJoCcPynPBJe0BW6HOwsSATxPu1k2LQ0bgeuJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:value: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2023-12-27T21:23:50Z"
      name: react-app-public-emailjs-template-id
      namespace: kitapkurdu
