---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: react-app-public-emailjs-service-id
  namespace: kitapkurdu
spec:
  encryptedData:
    value: AgCQQG1j8J6M7IcVdo4rcBJSlWt52oZhg9MWu0Feqwq36ntT4kMLHihp+4nnXRYU9P9QE9f6yIKqKbfEOBmWZ3z0mWgiI5LGvn0S9V+D/TlbdeMMaCgy7w8hXJJvQL8XSNd5KSAj83ALbaG2r7VeQSujs8jFndArXq/a2sDh5tA1n9Z7QVARApMpGx1JUGWOAKbXU2E8X+ASGHwtrumSswWdcio5SDvbuZ2tR/9GeB4iXtTrxwVmgysl9xH6m3+7T0Wn5GF9EjIo/uZWSOx85LvEoD40GDADOyiy4w1QrjXYyxCfP0EiICoHpUIi8xHcaGEG6EgDAu+YxrUOBMh7Qe7MBkGp/gPH/Ae6FLxmqLbSo+Q5uiLBSReRqLAesVPA9yMcaEzkaEmcniS4Cd/z75efwBrcFA+jmuvTzd9W74e5gd4OJVakak+r0GqT904vTCCHliBP9hwd5aPKunQpNJDSV3Pk+a6r/QCBW/NnIEEoQAU8vAU5QWikiTdCkEu6FGcpxk1kn3JyTEG7YgFYnQuo/Xs8uF81Ch1Y/5Zb5T4qfnqXoiOAY57CEFlgoVPl3tTRa0ixrSD0DSR8/6RdI96f1CWVNMgRx1h2FJvGFoA0DLPAwb5VMmMePLtzEwOTHLwLqkqbq5xl9JKcgcchRD9I3EDb6f3BskYZb1WCg+GH3N8bRaketBnyeVdwiHt1IHmUw4troatNSCUqzKyZx44=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:value: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2023-12-27T21:23:23Z"
      name: react-app-public-emailjs-service-id
      namespace: kitapkurdu
