apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kitapkurdu
  labels:
    team: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sayinmehmet47/backend-kitapkurdu-1:latest
          env:
            - name: MONGO_URI
              value: '***'
            - name: JWT_SECRET
              value: 'fsafdafdasfdk'
            - name: PORT
              value: '5000'
          ports:
            - containerPort: 5000
          resources:
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kitapkurdu
spec:
  type: NodePort 
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30003
# --- 
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-service
#   # namespace: kitapkurdu
# spec:
#   type: ExternalName
#   externalName: 'mongodb+srv://sayinmehmet47:Mardin.1992,@cluster0.ywv3z.mongodb.net/kitaplar?retryWrites=true&w=majority'