name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl

        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Create .kube/config
        run: |
          cat <<EOF > $HOME/.kube/config
          apiVersion: v1
          kind: Config
          clusters:
          - name: rancher
            cluster:
              server: "https://rancher.riwi.dev/k8s/clusters/c-m-cp898j4l"

          users:
          - name: rancher
            user:
              token: ${{ secrets.KUBE_CONFIG_TOKEN }}


          contexts:
          - name: rancher
            context:
              user: rancher
              cluster: rancher
              namespace: kitapkurdu

          current-context: rancher
          EOF
      - name: Deploy using kubectl
        run: |
          kubectl apply -f infra/k8s/ -n kitapkurdu
          kubectl apply -f secrets/ -n kitapkurdu
