name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd client && docker build -t sayinmehmet47/client-kitapkurdu-1 .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sayinmehmet47/client-kitapkurdu-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Create .kube/config
        run: |
          cat <<EOF > $HOME/.kube/config
          apiVersion: v1
          kind: Config
          clusters:
          - name: rancher
            cluster:
              server: "https://rancher.riwi.dev/k8s/clusters/c-m-cp898j4l"
          users:
          - name: rancher
            user:
              token: ${{ secrets.KUBE_CONFIG_TOKEN }}
          contexts:
          - name: rancher
            context:
              user: rancher
              cluster: rancher
              namespace: kitapkurdu
          current-context: rancher
          EOF

      - name: Deploy using kubectl
        run:  kubectl rollout restart deployment/frontend-deployment -n kitapkurdu