name: Client Build & Deploy

on:
  push:
    branches: [dev]
    paths:
      - 'client/**'

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: cd client

      - name: set version
        run: echo "TAG_VERSION=dev.$(date +'%y-%m-%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: client/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sayinmehmet47/client-kitapkurdu-1:dev
            sayinmehmet47/client-kitapkurdu-1:${{ env.TAG_VERSION }}
      - name: Deploy to Kubernetes
        run: |
          kubectl config set-cluster kubernetes \
          --server="https://rancher.riwi.dev/k8s/clusters/c-m-cp898j4l"
           kubectl config set-credentials github-action \
          --token=${{ secrets.KUBE_CONFIG_TOKEN }}
           kubectl config set-context default \
           --cluster=kubernetes \
           --user=github-action
           kubectl config use-context default
           kubectl set image deployment/frontend-deployment-dev frontend=sayinmehmet47/client-kitapkurdu-1:${{ env.TAG_VERSION }} -n kitapkurdu
    env:
      KUBECONFIG: kubeconfig
